-- Insert movies
INSERT INTO movies (title, description, duration, poster_url) VALUES
('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 142, 'https://example.com/posters/shawshank.jpg'),
('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 175, 'https://example.com/posters/godfather.jpg'),
('The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 152, 'https://example.com/posters/darkknight.jpg'),
('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 154, 'https://example.com/posters/pulpfiction.jpg'),
('Fight Club', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.', 139, 'https://example.com/posters/fightclub.jpg'),
('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 148, 'https://example.com/posters/inception.jpg'),
('The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 136, 'https://example.com/posters/matrix.jpg'),
('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.', 142, 'https://example.com/posters/forrestgump.jpg'),
('The Lord of the Rings: The Fellowship of the Ring', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 178, 'https://example.com/posters/lotr1.jpg'),
('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.', 146, 'https://example.com/posters/goodfellas.jpg'),
('The Silence of the Lambs', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 118, 'https://example.com/posters/silence.jpg'),
('Schindler''s List', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 195, 'https://example.com/posters/schindler.jpg'),
('The Green Mile', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', 189, 'https://example.com/posters/greenmile.jpg'),
('The Prestige', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.', 130, 'https://example.com/posters/prestige.jpg'),
('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 169, 'https://example.com/posters/interstellar.jpg'),
('The Departed', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 151, 'https://example.com/posters/departed.jpg'),
('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 155, 'https://example.com/posters/gladiator.jpg'),
('The Social Network', 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.', 120, 'https://example.com/posters/socialnetwork.jpg'),
('The Grand Budapest Hotel', 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.', 99, 'https://example.com/posters/grandbudapest.jpg'),
('Whiplash', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student''s potential.', 106, 'https://example.com/posters/whiplash.jpg'),
('Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 132, 'https://example.com/posters/parasite.jpg'),
('Joker', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.', 122, 'https://example.com/posters/joker.jpg'),
('1917', 'April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.', 119, 'https://example.com/posters/1917.jpg'),
('Once Upon a Time in Hollywood', 'A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood''s Golden Age in 1969 Los Angeles.', 161, 'https://example.com/posters/onceuponatime.jpg'),
('The Irishman', 'Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family in this acclaimed film from Martin Scorsese.', 209, 'https://example.com/posters/irishman.jpg'),
('Knives Out', 'A detective investigates the death of a patriarch of an eccentric, combative family.', 130, 'https://example.com/posters/knivesout.jpg'),
('Marriage Story', 'Noah Baumbach''s incisive and compassionate look at a marriage breaking up and a family staying together.', 137, 'https://example.com/posters/marriagestory.jpg'),
('Little Women', 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.', 135, 'https://example.com/posters/littlewomen.jpg'),
('The Farewell', 'A Chinese family discovers their grandmother has only a short while left to live and decide to keep her in the dark, scheduling a wedding to gather before she dies.', 100, 'https://example.com/posters/farewell.jpg'),
('Jojo Rabbit', 'A young boy in Hitler''s army finds out his mother is hiding a Jewish girl in their home.', 108, 'https://example.com/posters/jojorabbit.jpg'),
('Dune', 'Feature adaptation of Frank Herbert''s science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.', 155, 'https://example.com/posters/dune.jpg'),
('No Time to Die', 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help.', 163, 'https://example.com/posters/notimetodie.jpg'),
('The French Dispatch', 'A love letter to journalists set in an outpost of an American newspaper in a fictional 20th-century French city that brings to life a collection of stories published in "The French Dispatch".', 108, 'https://example.com/posters/frenchdispatch.jpg'),
('West Side Story', 'An adaptation of the 1957 musical, West Side Story explores forbidden love and the rivalry between the Jets and the Sharks, two teenage street gangs of different ethnic backgrounds.', 156, 'https://example.com/posters/westsidestory.jpg'),
('The Power of the Dog', 'Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.', 126, 'https://example.com/posters/powerofthedog.jpg'),
('Licorice Pizza', 'The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.', 133, 'https://example.com/posters/licoricepizza.jpg'),
('Nightmare Alley', 'A grifter working his way up from low-ranking carnival worker to lauded psychic medium matches wits with a psychiatrist bent on exposing him.', 150, 'https://example.com/posters/nightmarealley.jpg'),
('The Tragedy of Macbeth', 'A Scottish lord becomes convinced by a trio of witches that he will become the next King of Scotland, and his ambitious wife supports him in his plans of seizing power.', 105, 'https://example.com/posters/macbeth.jpg'),
('Spencer', 'During her Christmas holidays with the royal family at the Sandringham estate in Norfolk, England, Diana Spencer, struggling with mental health problems, decides to end her decade-long marriage to Prince Charles.', 117, 'https://example.com/posters/spencer.jpg'),
('The Lost Daughter', 'A woman''s beach vacation takes a dark turn when she begins to confront the troubles of her past.', 121, 'https://example.com/posters/lostdaughter.jpg'),
('Drive My Car', 'A widowed actor who relies on his chauffeur to drive him around while he works on a production of Uncle Vanya.', 179, 'https://example.com/posters/drivemycar.jpg'),
('Belfast', 'A young boy and his working-class Belfast family experience the tumultuous late 1960s.', 98, 'https://example.com/posters/belfast.jpg'),
('CODA', 'As a CODA (Child of Deaf Adults) Ruby is the only hearing person in her deaf family. When the family''s fishing business is threatened, Ruby finds herself torn between pursuing her passion at Berklee College of Music and her fear of abandoning her parents.', 111, 'https://example.com/posters/coda.jpg'),
('Don''t Look Up', 'Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.', 138, 'https://example.com/posters/dontlookup.jpg'),
('The Batman', 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city''s hidden corruption and question his family''s involvement.', 176, 'https://example.com/posters/batman.jpg'),
('Everything Everywhere All at Once', 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.', 139, 'https://example.com/posters/everythingeverywhere.jpg'),
('Top Gun: Maverick', 'After more than thirty years of service as one of the Navy''s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.', 131, 'https://example.com/posters/topgun.jpg'),
('Elvis', 'The life of American music icon Elvis Presley, from his childhood to becoming a rock and movie star in the 1950s while maintaining a complex relationship with his manager, Colonel Tom Parker.', 159, 'https://example.com/posters/elvis.jpg'),
('Avatar: The Way of Water', 'Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na''vi race to protect their planet.', 192, 'https://example.com/posters/avatar2.jpg'),
('Black Panther: Wakanda Forever', 'The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T''Challa.', 161, 'https://example.com/posters/blackpanther2.jpg'),
('Glass Onion: A Knives Out Mystery', 'Famed Southern detective Benoit Blanc travels to Greece for his latest case.', 139, 'https://example.com/posters/glassonion.jpg'),
('The Fabelmans', 'Growing up in post-World War II era Arizona, young Sammy Fabelman aspires to become a filmmaker as he reaches adolescence, but soon discovers a shattering family secret and explores how the power of films can help him see the truth.', 151, 'https://example.com/posters/fabelmans.jpg'),
('Women Talking', 'Do nothing. Stay and fight. Or leave. In 2010, the women of an isolated religious community grapple with reconciling their reality with their faith.', 104, 'https://example.com/posters/womentalking.jpg'),
('Tár', 'Set in the international world of Western classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and first-ever female chief conductor of a major German orchestra.', 158, 'https://example.com/posters/tar.jpg');

-- Insert sessions (5 sessions per movie)
INSERT INTO sessions (movie_id, start_time, hall, price) VALUES
-- Movie 1 sessions
(1, '2024-05-01 10:00:00', 'Hall 1', 350.00),
(1, '2024-05-01 13:30:00', 'Hall 2', 350.00),
(1, '2024-05-01 17:00:00', 'Hall 3', 400.00),
(1, '2024-05-01 20:30:00', 'Hall 1', 400.00),
(1, '2024-05-02 10:00:00', 'Hall 2', 350.00),

-- Movie 2 sessions
(2, '2024-05-01 11:00:00', 'Hall 2', 400.00),
(2, '2024-05-01 14:30:00', 'Hall 3', 400.00),
(2, '2024-05-01 18:00:00', 'Hall 1', 450.00),
(2, '2024-05-01 21:30:00', 'Hall 2', 450.00),
(2, '2024-05-02 11:00:00', 'Hall 3', 400.00),

-- Movie 3 sessions
(3, '2024-05-01 12:00:00', 'Hall 3', 450.00),
(3, '2024-05-01 15:30:00', 'Hall 1', 450.00),
(3, '2024-05-01 19:00:00', 'Hall 2', 500.00),
(3, '2024-05-01 22:30:00', 'Hall 3', 500.00),
(3, '2024-05-02 12:00:00', 'Hall 1', 450.00),

-- Movie 4 sessions
(4, '2024-05-01 10:30:00', 'Hall 1', 350.00),
(4, '2024-05-01 14:00:00', 'Hall 2', 350.00),
(4, '2024-05-01 17:30:00', 'Hall 3', 400.00),
(4, '2024-05-01 21:00:00', 'Hall 1', 400.00),
(4, '2024-05-02 10:30:00', 'Hall 2', 350.00),

-- Movie 5 sessions
(5, '2024-05-01 11:30:00', 'Hall 2', 400.00),
(5, '2024-05-01 15:00:00', 'Hall 3', 400.00),
(5, '2024-05-01 18:30:00', 'Hall 1', 450.00),
(5, '2024-05-01 22:00:00', 'Hall 2', 450.00),
(5, '2024-05-02 11:30:00', 'Hall 3', 400.00);

-- Insert bookings (10 bookings per session)
INSERT INTO bookings (session_id, seat_number, customer_name, customer_email) VALUES
-- Session 1 bookings
(1, 1, 'John Smith', 'john.smith@example.com'),
(1, 2, 'Jane Doe', 'jane.doe@example.com'),
(1, 3, 'Robert Johnson', 'robert.johnson@example.com'),
(1, 4, 'Emily Davis', 'emily.davis@example.com'),
(1, 5, 'Michael Wilson', 'michael.wilson@example.com'),
(1, 6, 'Sarah Brown', 'sarah.brown@example.com'),
(1, 7, 'David Miller', 'david.miller@example.com'),
(1, 8, 'Lisa Taylor', 'lisa.taylor@example.com'),
(1, 9, 'James Anderson', 'james.anderson@example.com'),
(1, 10, 'Patricia Thomas', 'patricia.thomas@example.com'),

-- Session 2 bookings
(2, 1, 'Christopher White', 'christopher.white@example.com'),
(2, 2, 'Jennifer Harris', 'jennifer.harris@example.com'),
(2, 3, 'Daniel Martin', 'daniel.martin@example.com'),
(2, 4, 'Nancy Thompson', 'nancy.thompson@example.com'),
(2, 5, 'Matthew Garcia', 'matthew.garcia@example.com'),
(2, 6, 'Betty Martinez', 'betty.martinez@example.com'),
(2, 7, 'Anthony Robinson', 'anthony.robinson@example.com'),
(2, 8, 'Margaret Clark', 'margaret.clark@example.com'),
(2, 9, 'Mark Rodriguez', 'mark.rodriguez@example.com'),
(2, 10, 'Dorothy Lewis', 'dorothy.lewis@example.com'),

-- Session 3 bookings
(3, 1, 'Donald Lee', 'donald.lee@example.com'),
(3, 2, 'Sandra Walker', 'sandra.walker@example.com'),
(3, 3, 'Paul Hall', 'paul.hall@example.com'),
(3, 4, 'Ashley Allen', 'ashley.allen@example.com'),
(3, 5, 'Steven Young', 'steven.young@example.com'),
(3, 6, 'Kimberly Hernandez', 'kimberly.hernandez@example.com'),
(3, 7, 'Andrew King', 'andrew.king@example.com'),
(3, 8, 'Donna Wright', 'donna.wright@example.com'),
(3, 9, 'Kenneth Lopez', 'kenneth.lopez@example.com'),
(3, 10, 'Carol Hill', 'carol.hill@example.com'),

-- Session 4 bookings
(4, 1, 'George Scott', 'george.scott@example.com'),
(4, 2, 'Michelle Green', 'michelle.green@example.com'),
(4, 3, 'Edward Adams', 'edward.adams@example.com'),
(4, 4, 'Amanda Baker', 'amanda.baker@example.com'),
(4, 5, 'Brian Gonzalez', 'brian.gonzalez@example.com'),
(4, 6, 'Melissa Nelson', 'melissa.nelson@example.com'),
(4, 7, 'Ronald Carter', 'ronald.carter@example.com'),
(4, 8, 'Deborah Mitchell', 'deborah.mitchell@example.com'),
(4, 9, 'Timothy Perez', 'timothy.perez@example.com'),
(4, 10, 'Stephanie Roberts', 'stephanie.roberts@example.com'),

-- Session 5 bookings
(5, 1, 'Jason Turner', 'jason.turner@example.com'),
(5, 2, 'Rebecca Phillips', 'rebecca.phillips@example.com'),
(5, 3, 'Jeffrey Campbell', 'jeffrey.campbell@example.com'),
(5, 4, 'Sharon Parker', 'sharon.parker@example.com'),
(5, 5, 'Ryan Evans', 'ryan.evans@example.com'),
(5, 6, 'Cynthia Edwards', 'cynthia.edwards@example.com'),
(5, 7, 'Jacob Collins', 'jacob.collins@example.com'),
(5, 8, 'Kathleen Stewart', 'kathleen.stewart@example.com'),
(5, 9, 'Gary Sanchez', 'gary.sanchez@example.com'),
(5, 10, 'Amy Morris', 'amy.morris@example.com'); 